POST http://localhost:8080/import
Content-Type: application/json


 [ " https://infokam.su/kamyshin-ozhidayut-tumany-i-dozhdi.ht",
 "http://admkamyshin.info/ugohs"]


###

POST http://localhost:8080/import/ready
Content-Type: application/json

 [{"ready":"https://goo.su/7tKW","target":" https://infokam.su/kamyshin-ozhidayut-tumany-i-dozhdi.ht"},
   {"ready":" https://goo.su/7Tko","target": " http://admkamyshin.info/ugohs"}]

###

GET http://localhost:8080/save?url=https://www.profildoors.ru/catalog/seriya_smk/
###

###
GET localhost:8080/go/7ra

###
GET http://localhost:8080/save?url=https://google.com

###
GET localhost:8080/go/7q6
###
GET http://localhost:8080/save?url=https://profildoors-doors.ru/serija-smk/
###
GET localhost:8080/go/7sd
###
GET http://localhost:8080/save?url=https://chrome.google.com/webstore/detail/talend-api-tester-free-ed/aejoelaoggembcahagimdiliamlcdmfm
###
GET localhost:8080/go/7sn
###
