apiVersion: v1
kind: Service
metadata:
  name: postgresql-dev-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-dev-db
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql-dev-db-secret
data:
  database: ZGV2ZGI=                      # echo "devdb" | base64
  username: ZGV2ZGJfb3duZXI=              # echo "devdb_owner" | base64
  password: cGFzc3dvcmQ=                  # echo "password" | base64
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-dev-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-dev-db
  labels:
    app.kubernetes.io/name: postgresql-dev-db
spec:
  serviceName: postgresql-dev-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-dev-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-dev-db
    spec:
      containers:
        - name: postgres
          image: postgres:13.1
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgresql-dev-db-pvc
