apiVersion: v1
kind: Service
metadata:
  name: short-url-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-dev-db