#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: short-url
#  labels:
#    app.kubernetes.io/name: short-url
#imagePullSecrets:
#  - name: dockerreg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url
  labels:
    app.kubernetes.io/name: short-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: short-url
  template:
    metadata:
      labels:
        app.kubernetes.io/name: short-url
    spec:
      containers:
        - name: short-url
          image: docker.io/teiwas/short-url
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: short-url-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: short-url-db-secret
                  key: password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: short-url-db-secret
                  key: database
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: short-url-db-secret
                  key: database
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          # reads: application.properties
          volumeMounts:
            - name: short-url-config
              mountPath: /config
      volumes:
        - name: short-url-config
          configMap:
            name: short-url-config-map
            optional: true
